#!/bin/sh

# run the script via rosrun (for python scripts a simple symlink would also
# work but using rosrun works for C++ executables as well)

export DISPLAY=:1
rosrun rrc run_physical_episode.py "$@"
