name: rrc_phase_2_simulation
channels:
- pytorch
- conda-forge
dependencies:
- python=3.6.9
- numpy==1.19.1
- pinocchio==2.4.7
- pip==20.1.1
- pytorch=1.4.0=py3.6_cuda10.1.243_cudnn7.6.3_0
- torchvision=0.5.0=py36_cu101
- pip:
  - pybullet==2.8.4
  - gym==0.17.2
  - opencv-python==4.2.0.34
  - catkin-pkg==0.4.22
  # the packages below are required to run the example (training with ppo) which
  # we provide. if you do not wish to execute the example, you may safely remove
  # them
  - tensorflow==1.15.0
  - pandas==0.24.2
  - joblib==0.16.0
  - stable-baselines==2.10.0
  - pyyaml==5.3.1
  - gin-config==0.3.0
  - imageio==2.9.0
  - cvxopt==1.2.5
  - cvxpy==1.1.5
  - git+https://github.com/ripl-ttic/pybullet_planning.git@rrc_phase1
  - git+https://github.com/cbschaff/dl.git@rrc_phase1
