# This is an example config for train_ppo.py that can be used to run it locally.
logdir: ./test_logs
base_config: python/code/configs/residual_ppo.gin
gin_bindings:
    make_pybullet_env.goal_difficulty: 2
    make_pybullet_env.termination_fn: position_close_to_goal
